### ISSUE TITLE
Python 3.5 support?

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/gemma-zds-client#9]
@sergei-maertens ik weet dat je fan bent van f-strings, maar voor een library is het gebruik ervan (en daardoor een harde Python 3.6 eis) best wel vervelend.

Sta je ervoor open dat we dit aanpassen?

**Comment by sergei-maertens** [comment]
Ja, was tot nu toe makkelijk doordat het enkel in Python 3.6 omgevingen (Docker) gebruikt werd. Zolang het geen maintenance-burden is, vind ik het prima.

**Comment by sergei-maertens** [comment]
We testen op Python 3.5, 3.6 en 3.7, zie [travis](https://travis-ci.org/VNG-Realisatie/gemma-zds-client)
